name: Angular CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Run unit tests (Headless)
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb
          xvfb-run npm run test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage
